version: '2'
services: 
  postgres: 
    image: postgres
    container_name: rails_db
  web: 
    build: .    
    container_name: rails_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
       - .:/app
    ports: 
       - "8080:3000"
    depends_on:
       - postgres